name: custom-additions-checks
on:
  push:
    branches:
      - main

jobs:
  unit_tests:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install pytest
      run: pip install pytest
    - name: Unit test
      run: pytest test_custom_trl.py
    