name: custom-additions-checks
on:
  push:
    branches:
      - develop

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pytest
        run: pip install pytest
      - name: Unit test
        run: pytest test_custom_trl.py